### ISSUE TITLE
Veloctity Proxy support

### ISSUE THREAD

**Issue by myavuzokumus** [ZorgBtw/BungeeSK#15]

**Comment by ZorgBtw** [comment]
Hey ! Thanks for reaching me out. At the moment, i'm not sure the Velocity API can allow BungeeSK to use its fully power, and all of its effects/expressions.

**Comment by myavuzokumus** [comment]
You can at least make a different addon suitable for Velocity, it might be called VelocitySK.

**Comment by ZorgBtw** [comment]
No, I actually have to maintain BungeeSK alive, so I would'nt make another Skript addon now.

**Comment by myavuzokumus** [comment]
Still can't add additional Velocity support?
