### ISSUE TITLE
make %bungeeserver% execute console command doesn't work

### ISSUE THREAD

**Issue by UsainSrht** [ZorgBtw/BungeeSK#16]
**Describe the bug**
make %bungeeserver% execute console command doesn't work

**To Reproduce**
!make (bungee server named "survival") execute console command "say s"

**Expected behavior**
Work

**Screenshots**
![image](https://user-images.githubusercontent.com/59025999/147780598-bcfe4ce2-d827-453c-b533-942cb8533a85.png)

**Desktop (please complete the following information):**
 - OS: Linux x64
 - Spigot version 1.18.1
 - BungeeSK version 1.1.0

**Additional context**
There's no console error/message on both spigot and bungee consoles.
make bungee/all servers execute console command is working

**Comment by ZorgBtw** [comment]
![image](https://user-images.githubusercontent.com/67600687/147781599-a080473d-8e07-41cd-a182-629c4541a7e7.png)

its working for me, try using the newest version available [here](https://github.com/ZorgBtw/BungeeSK/suites/4795817820/artifacts/134353659)

**Comment by UsainSrht** [comment]
> ![image](https://user-images.githubusercontent.com/67600687/147781599-a080473d-8e07-41cd-a182-629c4541a7e7.png)
> 
> its working for me, try using the newest version available [here](https://github.com/ZorgBtw/BungeeSK/suites/4795817820/artifacts/134353659)

downloaded and installed latest(2.0.0) version on both spigot and bungee servers but it didn't change anything.
![image](https://user-images.githubusercontent.com/59025999/147792047-b8ea4a51-2252-4a13-9b1d-e19c4fd61cf9.png)

**Comment by ZorgBtw** [comment]
Should be fixed in v2.0.0, download it [here](https://github.com/ZorgBtw/BungeeSK/suites/7627250624/artifacts/316917511)
