### ISSUE TITLE
Can't disconnect crashed server

### ISSUE THREAD

**Issue by UsainSrht** [ZorgBtw/BungeeSK#18]
**Describe the bug**
When a backend server that connected to bungeesk crashes it doesn't get removed from bungeesk connections. And even you can't disconnect it manually. So you have to disconnect all servers and connect one by one again.

**To Reproduce**
Connect one of your backend servers to bungeesk
kill the process of thtat backend server
try to disconnect that server in bungee console

**Expected behavior**
Removal of disconnected connection on bungee side.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/59025999/178942011-c3da5dc6-d268-48d5-bea7-14e0a2412663.png)
![Screenshot_2](https://user-images.githubusercontent.com/59025999/178942381-24eabeae-2e57-4e22-af18-6a3a49bf2899.png)

**Desktop (please complete the following information):**
 - OS: Centos 7 64x
 - Spigot version: 119
 - BungeeSK version 2.0.0

**Additional context**
I have 2 backend servers. One of them are connected and it didn't shown in the bungeesk servers list.
I can't disconnect manually. Both connected and disconnected servers. Everytime I have to disconnect all servers and connect them all one by one again.

You can add keepalive to the plugin. It'll check the connections and if there's no respond it'll disconnects that server and tries to connect again.

**Comment by MrY3llow** [comment]
Hey!
I also have the same problem but a little bit different :
the lobby can't get the info from the proxy (such as connected players, co servers, etc).
What happens is that the lobby disconnects from the proxy but the proxy doesn't want the lobby to reconnect.

**To solve the problem temporarily** I have to do `bungeesk disconnect 127.0.0.1:30001` in the proxy console to disconnect the lobby then it reconnects itself.
The weirdest thing is that the lobby understands that it is disconnected from the proxy and wants to reconnect but the proxy doesn't allow the connection and says that there is already a server connected with this ip/port exactly like you.

Another amazing thing is that it happens at totally random times xD. So I have to be ready at any time to fix the problem and do what I explained in the paragraph above.

I found these 2 errors (which are the same) that occur in the proxy console when the bug appears (The 2 errors are sure to occur on 2 different days) :
```
[21:13:39] [Thread-13/ERROR]: Exception in thread "Thread-13" java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.connection.Server.getInfo()" because the return value of "net.md_5.bungee.api.connection.ProxiedPlayer.getServer()" is null
[21:13:39] [Thread-13/ERROR]:     at fr.zorg.bungeesk.bungee.sockets.ClientServer.read(ClientServer.java:398)
[21:13:39] [Thread-13/ERROR]:     at java.base/java.lang.Thread.run(Thread.java:833)
```
```
[13:02:13] [Thread-10/ERROR]: Exception in thread "Thread-10" java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.connection.Server.getInfo()" because the return value of "net.md_5.bungee.api.connection.ProxiedPlayer.getServer()" is null
[13:02:13] [Thread-10/ERROR]:     at fr.zorg.bungeesk.bungee.sockets.ClientServer.read(ClientServer.java:398)
[13:02:13] [Thread-10/ERROR]:     at java.base/java.lang.Thread.run(Thread.java:833)
```


**Configuration**

Proxy :
- Waterfall 1.19-498
- BungeeSK V1.1.1

Lobby :
- Paper 1.18.2-302
- Skript 2.6.1
- BungeeSK 1.1.1

**Comment by ZorgBtw** [comment]
Should be fixed in v2.0.0, download it [here](https://github.com/ZorgBtw/BungeeSK/suites/7627250624/artifacts/316917511)

**Comment by UsainSrht** [comment]
> Should be fixed in v2.0.0, download it [here](https://github.com/ZorgBtw/BungeeSK/suites/7627250624/artifacts/316917511)

It seemed to be fixed at first but now I had a short internet connection and backend servers disconnected but they still show up in bungee

![image](https://user-images.githubusercontent.com/59025999/183488018-0c397cc5-6756-4b81-bda1-eaea57e3b881.png)

and also found strange ip in results of /bungeesk servers 
`193.124.7.9:0`

**Comment by UsainSrht** [comment]
I disconnected all servers from bungee console with `bungeesk disconnect all`
but backends still thought they are connected `send "s" if client is conned`
I manually did `disconnect the client` and run connect skript.

**Comment by UsainSrht** [comment]
@ZorgBtw

**Comment by ZorgBtw** [comment]
Can you please try using [this version](https://github.com/ZorgBtw/BungeeSK/suites/7637109400/artifacts/317546566) ?

**Comment by UsainSrht** [comment]
I'll asap
