### ISSUE TITLE
“On bungee player leave:” only valid on one server？

### ISSUE THREAD

**Issue by xibo1212** [ZorgBtw/BungeeSK#19]
This monitor only works in the lobby server, but other sub servers don't work. Why？

on bungee player leave:
	send "&3leave" to console

**Comment by ZorgBtw** [comment]
Should be fixed in v2.0.0, download it [here](https://github.com/ZorgBtw/BungeeSK/suites/7627250624/artifacts/316917511)

**Comment by xibo1212** [comment]
Perfect thank you
