### ISSUE TITLE
Global Variables not working

### ISSUE THREAD

**Issue by realago** [ZorgBtw/BungeeSK#20]
I'm using BungeeSk for a while now (1.10), and I didn't touch anything, but none of my global variables are working anymore. They were fine about 20 minutes ago, and just stopped.

I've tried just using test ones instead of the actual ones, and it still doesn't work:

```
command /testing:
 trigger:
  set global variable "money.%player's uuid%" to "10"
  set {player.money} to global variable "money.%player's uuid%"
  message "&7You have &a%{player.money}%"
```

This code should work as it is almost identical from the wiki, but it comes up as <none> when I run the command. I tried swapping out versions to the latest development build and still nothing.

Is it also possible to make it where you can set the global variable to a boolean, string, or integer? Because right now I get an error saying I can only use string, which isn't ideal.

Also maybe some sort of "adding" to a global variable instead of setting it to local one, then adding it, and setting it back.

**Comment by ZorgBtw** [comment]
I think you should use the v2 version of BungeeSK which is in development, downloadable [here](https://github.com/ZorgBtw/BungeeSK/suites/7637109400/artifacts/317546566). About global variables, they can now be set to some others types, you can find a guide [here](https://bungeesk.zorg-dev.fr/basic-usage/global-variables)

**Comment by realago** [comment]
Perfect thank you
