### ISSUE TITLE
Execute bungeecord command as player

### ISSUE THREAD

**Issue by Soufreur78** [ZorgBtw/BungeeSK#21]
Is it possible to add the ability to make players execute bungeecord commands?

The Skungee addon does but obviously BungeeSk does not.

For example, it would be useful for me to run bungeecord commands like /ban from the /ss menu I created.

The expression could look like this:
`- "make bungee player named "Notch" execute (bungeecord/server) command "say What's up people!""
- make bungee[cord] [server] execute console command %string% [as bungee player named "Notch"]`

Thank for your job !

**Comment by ZorgBtw** [comment]
https://skripthub.net/docs/?id=5688

**Comment by Soufreur78** [comment]
> https://skripthub.net/docs/?id=5688

I saw this expression, but it's doesn't work with bungeecoord command.

It says "This command does not exist..."

**Comment by ZorgBtw** [comment]
> > https://skripthub.net/docs/?id=5688
> 
> I saw this expression, but it's doesn't work with bungeecoord command.
> 
> It says "This command does not exist..."

It actually makes the player execute a Bungeecord command, not a Spigot command.
What you're requesting to make a player execute a command such as /say for example, however the /say command is a Spigot command and not a Bungeecord one.

**Comment by Soufreur78** [comment]
You can do the test with a bungeecord command like /glist or /send etc... , it won't work!

```
command /test:
trigger:
make bungee player named "%player%" execute command "glist"
```

It says "This command doesn't exist"

**Comment by ZorgBtw** [comment]
Have you tried [this version](https://github.com/ZorgBtw/BungeeSK/suites/7637109400/artifacts/317546566) ? Let me know if it works

**Comment by ZorgBtw** [comment]
Added in https://github.com/ZorgBtw/BungeeSK/commit/093c998af7028d23d8084003251f29575a89c0d2
