### ISSUE TITLE
BungeeSK +2.0.0 ，Where can I download it，please？

### ISSUE THREAD

**Issue by xibo1212** [ZorgBtw/BungeeSK#24]

**Comment by JohnHeikens** [comment]
go to his discord:
https://discord.gg/p96jeRqwkD

**Comment by xibo1212** [comment]
Sorry, my country can't open this

**Comment by JohnHeikens** [comment]
try the dev branch 😊

**Comment by JohnHeikens** [comment]
[BungeeSK_3.zip](https://github.com/ZorgBtw/BungeeSK/files/9713186/BungeeSK_3.zip)

**Comment by xibo1212** [comment]
Thank you very much!

**Comment by JohnHeikens** [comment]
no problem :D
