### ISSUE TITLE
This BungeeServer bug

### ISSUE THREAD

**Issue by ArcadeProgram** [ZorgBtw/BungeeSK#28]
### **Describe the bug**
Le `this bungeeserver` ne renvoie rien si le proxy et le serveur sont sur la même IP, car BungeeSK ne get pas la bonne IP, mais plutôt un 127.0.0.1/0.0.0.0 ou 172.18.0.1

### **To Reproduce**
Utiliser `this bungeeserver` dans un serveur sur la même ip que le proxy.

### **Desktop (please complete the following information):**
 - OS: Linux 5.15.0-47-generic (amd64)
 - Spigot: 1.16.5 
 - BungeeSK: 2.0.0

### **Additional context**
Après avoir fait quelques tests, j'ai trouvé une petite idée pour régler les `this bungeeserveur`
En gros, les serveurs sur une IP différentes sont détectés.
Donc, quand BungeeSK tentera de get this server, il faut qu'il check si la valeur retournée est set.

Si elle n'est pas set, alors cela signifie que le serveur possède la même IP que le proxy
Si il y a besoin de plus de précisions sur mon idée, n'hésite pas 🙂

**2 ème solution :**
Il faut check si l'IP du this bungeeserver est `0.0.0.0`, `127.0.0.1` ou `172.18.0.1`

À partir de là, on sais que le serveur est sur la même IP que le proxy, il peut donc get le serveur, non pas avec l'ip détecté, mais avec la véritable IP du proxy (à get dans la config, par exemple)

**Comment by ZorgBtw** [comment]
Useless. Closing it.
