### ISSUE TITLE
Bungeecord 1.20 not working

### ISSUE THREAD

**Issue by ringo360** [ZorgBtw/BungeeSK#30]
**Describe the bug**
BungeeSK fails to start due to the effect of a change in the dependency version of Snakeyaml.

**To Reproduce**
1. download Bungeecord 1.20 (latest build)
2. put BungeeSK into the plugins folder
3. Start Bungeecord.

**Expected behavior**
Nothing should happen, it should just start up normally.

**Screenshots**
Sorry, I don't have screenshots :(

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Spigot version: git-Purpur-1858 (MC: 1.19.2)
 - BungeeSK version: 2.0.0(last build)

**Additional context**
I also tried 1.1.0 with similar results.

**Comment by MrY3llow** [comment]
Yes thanks for the issue report! I have the same problem and I hope it will be fix soon ^^

**Comment by ZorgBtw** [comment]
Fixed in f86a0bf8fa5cc29c3d881bdbfc2b58ccd5fd1fbf. New jar downloadable [here](https://github.com/ZorgBtw/BungeeSK/suites/13866553958/artifacts/770505807)
