### ISSUE TITLE
BungeeSK n'envois plus de message (Velocity)

### ISSUE THREAD

**Issue by MrY3llow** [ZorgBtw/BungeeSK#31]
BungeeSK, en tout cas dans la version de mon serveur, continue d'envoyer les messages aux clients, mais les messages sont tous vides. (Comme s'il n'envoyait qu'ESPACE dans le chat ou dans la console).

### Comment reproduire le bug
- Utiliser le code suivant :
 Cela devrait envoyer "Hello World" dans le chat de tous les joueurs, mais ils recoivent " " a la place.
```
on load:
    loop all bungee players:
        send bungee message "Hello World" to loop-bungeeplayer
 ```
- Faire la commande `/bungeesk servers` devrait afficher la liste des serveurs connectés au proxy, mais le titre du message n'est pas envoyé (il y a juste la liste des serveurs et j'avais sur un autre serveur un titre supplémentaire qui ici est remplacé par " ")
 ![image](https://github.com/ZorgBtw/BungeeSK/assets/92597516/b73cde10-ddf0-43e0-9f9a-f8b472fd6044)
- Faire la commande `/bungeesk' envoie 4 lignes de textes vides
 ![image](https://github.com/ZorgBtw/BungeeSK/assets/92597516/e41ec550-22dc-4f84-8d4f-949158fa133d)

Ces messages _vides_ se produisent aussi dans la console du proxy.

### Liste de mes plugins
Serveur de jeu, Paper (purpur en réalité) :
 -  ![image](https://github.com/ZorgBtw/BungeeSK/assets/92597516/f34c2af5-831b-457d-ae20-63ad87dc02c4)

Proxy (Velocity) :
  - ![image](https://github.com/ZorgBtw/BungeeSK/assets/92597516/9b684584-88fd-4814-b582-a6fe313ab2ad)

### Configuration
Version serveur de jeu : purpur-1.20.1-2060
Version proxy : velocity-3.3.0-SNAPSHOT-306
Version Skript : 2.7.3
Version BungeeSK : 2.0.0 (j'ai trouvé le fichier ici : [annonce discord](https://discord.com/channels/827604115932446738/827605073482743878/1172940691249315840) )
Windows 10

**Comment by ZorgBtw** [comment]
Fixé dans 2a082954591dd68544c9dbc4bb8cd2ff0e436be7
