### ISSUE TITLE
[BungeeSK] BungeeSK couldn't find server with this address/port !

### ISSUE THREAD

**Issue by ghost** [ZorgBtw/BungeeSK#6]
Servers wont connect.

Bungee Config:
```
port: 1332
password: '-private-'
sendFilesAuto: false
whitelistIp: false
authorizedIp:
 - 127.0.0.1
```

Paper-Spigot Server skript:

```applescript
on load:
	while client is not connected: #Using a while loop to try to connect if the client is not connected
		create new bungee connection: #Creation of a new Bungeecord connection
			set address of connection to "127.0.0.1" #Use this IP if the Bungeecord is on the same machine
			set port of connection to 1332 #This port as to be opened if the specified client is not hosted on the same machine as the server
			set password of connection to "-private-'" #Complete your password here, this has to be the same as the one in the Bungeecord config
			set name of connection to "hub" #Name has to be unique, if the same name is already connected, the connection will end
		start new connection with last created connection #Sending connection request to the server
		wait 30 seconds #Waiting 30 seconds between 2 connection tries, it's recommended to not decrease this value
```

**Comment by Alessevan** [comment]
Please add errors of both console.

**Comment by ghost** [comment]
Proxy Console
![Screenshot 2021-04-27 at 11 42 16 AM](https://user-images.githubusercontent.com/82738886/116271084-a9eaf480-a74d-11eb-80ab-ea4197a90a89.png)

Spigot-Paper Console
![Screenshot 2021-04-27 at 11 42 02 AM](https://user-images.githubusercontent.com/82738886/116271093-aa838b00-a74d-11eb-89ce-63ff2d874e64.png)

**Comment by Alessevan** [comment]
Have you try to restart both instances (proxy and server) ?

**Comment by ghost** [comment]
yes

**Comment by Alessevan** [comment]
Ok, I managed to get the same error. It seems that you are trying to connect the client on the proxy with the bungee port and not with the BungeeSK port.
Please verify that the port 1332 from outside is redirected to the port 1332 inside the docker

**Comment by ghost** [comment]
the port 1332 is assigned to the proxy server

**Comment by Alessevan** [comment]
Yeah but it seems that when you are trying to connect on `127.0.0.1:1332` it redirects you to `ip of proxy's docker` at port `port of bungee`.

**Comment by ghost** [comment]
so would I need to put %ip of proxy%:%port of proxy%?

the proxy IP is : play.servername.net (cant release the actual IP for specific reasons)

**Comment by Alessevan** [comment]
No it's just because I don't know 'em. It can be everything.

**Comment by ghost** [comment]
@ZorgBtw can you try to help please

**Comment by ZorgBtw** [comment]
are you using something like pterodactyl ? if yes can you check if the port `1332` is opened ?

**Comment by ghost** [comment]
yes im using pterodactyl, and yes the port is opened. ADMIN CONTROL> Node> node.01> allocations

**Comment by Skylyxx** [comment]
Can you send the config.yml of BungeeSK ? (In the proxy)

**Comment by ghost** [comment]
config is in first post

**Comment by Skylyxx** [comment]
And your proxy's config ?

**Comment by ghost** [comment]
the bungeecord config?

**Comment by Skylyxx** [comment]
Yes

**Comment by ghost** [comment]
well im not comfortable sending that seeing as it contains all the ips and the server isn't public yet

**Comment by Skylyxx** [comment]
If you want, send me on discord: Skylyxx#8816

**Comment by ghost** [comment]
i send friend request

**Comment by ghost** [comment]
The issue was fixed. (i did a stupid mistake that I will regret forever)
Thanks to everyone who helped
